trigger:
  branches:
    include:
      - ramaTriger

pool:
  name: 'pool-jose'

steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-Dcucumber.filter.tags=@test'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true